### ISSUE TITLE
Anduril 2 today's release 2024-04-01 not working

### ISSUE THREAD

**Issue by dirtydancing** [ToyKeeper/anduril#55] opened 2024-04-01 18:12 UTC
Real bug report here, given today's date of April 1st: I checked with Emisar D2 (0135) and Emisar D1K (0125), and I cannot get Anduril 2 release 2024-04-01 to work. Both lights, coming from the previous official Anduril 2 release 2023-12-03, start blinking right after reflashing, and also right after connecting the battery. No clicking input is possible, also no hard reset, nothing changes the lights' blinking.

Some more details: With the dual-channel Emisar D2, it appears that Channel 1 was blinking, whereas Channel 2 was constantly on, both very bright. With the single-channel Emisar D1K, when connecting the battery several times, it was sometimes bright blinking, sometimes bright constant-on, and also one time just dark (at that point, today's hilarious dark mode release notes actually seemed to be real).

Both lights could be reflashed back to the previous Anduril 2 release 2023-12-03, and worked fine again, just like before. I have used Hank's reflashing kit and ZFlasher AVR with an Android phone. The blinking of both lights started right after "successfully completed" was displayed. Just to make sure I have also tried with a new battery, and I have cleaned all the lights' contacts, but all of that did not make a difference.

**Comment by Light-Veteran** [comment] 2024-04-01 19:09
The same here for Lume1 FW3X. Not working

**Comment by ToyKeeper** [comment] 2024-04-01 19:34
I think I see what happened.  On lights with "jump start", there was an infinite recursion error caused by Dark Mode.  This release was, obviously, tested thoroughly. :wink:

Fixed in 54119b91dac24b79464372046d3cf79db665179a, and I updated the release .zip file too.

**Closed as completed by ToyKeeper** 2024-04-01 19:34 UTC
